// Mẫu hóa đơn đăng ký với cơ quan thuế
export const INVOICE_TEMPLATES = [
  {
    code: '02GTTT0/001',
    name: 'Hóa đơn bán hàng',
    nameVi: 'Hóa đơn bán hàng (02/GTTT)',
    series: '2C24ABO',
    type: 'GTTT',
  },
]

import { getCompany } from '../store/companyStore'

// SELLER is always read from companyStore so it stays in sync with Settings → Thông tin công ty
export function getSeller() {
  const c = getCompany()
  return {
    name:        c.companyName,
    taxCode:     c.taxCode,
    address:     c.address,
    bankAccount: c.bankAccount,
    bankName:    `${c.bankName}${c.bankBranch ? ' — ' + c.bankBranch : ''}`,
    phone:       c.phone,
    email:       c.email,
    website:     c.website,
    symbol:      '1C24ABO',
    legalRep:    c.legalRep,
    legalRepTitle: c.legalRepTitle,
  }
}

// Backward-compat static snapshot (used by code that hasn't been updated yet)
export const SELLER = getSeller()

export const mockInvoices = [
  {
    id: 'INV-2024-001',
    sapBillingDoc: '9000000001',
    status: 'issued',
    issueDate: '2024-05-01',
    dueDate: '2024-05-31',
    taxAuthorityCode: '202400000001AB3F',
    templateCode: '01GTKT0/001',
    buyerName: 'James Anderson',
    billTo: 'ABC Technology Co., Ltd',
    billToCode: 'C001',
    paymentMethod: 'Bank Transfer / Cash',
    currency: 'VND',
    customer: {
      code: 'C001',
      name: 'ABC Technology Co., Ltd',
      taxCode: '0123456789',
      address: '123 Nguyen Hue Blvd, Ben Nghe Ward, District 1, Ho Chi Minh City',
      phone: '028-3822-1111',
      email: 'accounting@abctech.com',
      bankAccount: '',
      bankName: '',
    },
    items: [
      { id: 1, description: 'ERP Software – MM Module License', unit: 'License', qty: 1, unitPrice: 50000000, vatRate: 10 },
      { id: 2, description: 'Implementation Consulting Service', unit: 'Day', qty: 5, unitPrice: 8000000, vatRate: 10 },
    ],
    note: 'Payment via bank transfer',
    series: '1C24ABO',
    number: '00000001',
  },
  {
    id: 'INV-2024-002',
    sapBillingDoc: '9000000002',
    status: 'draft',
    issueDate: '2024-05-10',
    dueDate: '2024-06-10',
    buyerName: 'Sarah Mitchell',
    paymentMethod: 'Bank Transfer',
    currency: 'VND',
    customer: {
      code: 'C002',
      name: 'XYZ Group Corporation',
      taxCode: '9876543210',
      address: '456 Le Loi St., Ben Thanh Ward, District 1, Ho Chi Minh City',
      phone: '028-3911-2222',
      email: 'finance@xyzgroup.com',
      bankAccount: '1234567890',
      bankName: 'Vietcombank',
    },
    items: [
      { id: 1, description: 'Accounting Software License', unit: 'Year', qty: 2, unitPrice: 30000000, vatRate: 10 },
    ],
    note: '',
    series: '1C24ABO',
    number: '00000002',
  },
  {
    id: 'INV-2024-003',
    sapBillingDoc: '9000000003',
    status: 'cancelled',
    issueDate: '2024-04-15',
    dueDate: '2024-05-15',
    buyerName: 'Michael Chen',
    paymentMethod: 'Cash',
    currency: 'VND',
    customer: {
      code: 'C003',
      name: 'DEF Solutions JSC',
      taxCode: '1122334455',
      address: '789 Hai Ba Trung St., Ward 8, District 3, Ho Chi Minh City',
      phone: '028-3930-3333',
      email: 'finance@defsolutions.vn',
      bankAccount: '',
      bankName: '',
    },
    items: [
      { id: 1, description: 'System Maintenance Service', unit: 'Month', qty: 3, unitPrice: 15000000, vatRate: 8 },
    ],
    note: 'Cancelled per customer request',
    series: '1C24ABO',
    number: '00000003',
  },
]

// Mock Sales Orders from SAP SD module
export const mockSalesOrders = [
  {
    soNumber: '1000000001',
    soDate: '2024-04-20',
    deliveryDate: '2024-05-05',
    customer: {
      code: 'C001',
      name: 'ABC Technology Co., Ltd',
      taxCode: '0123456789',
      address: '123 Nguyen Hue Blvd, Ben Nghe Ward, District 1, Ho Chi Minh City',
      phone: '028-3822-1111',
      email: 'accounting@abctech.com',
      bankAccount: '',
      bankName: '',
    },
    buyerName: 'James Anderson',
    paymentMethod: 'Bank Transfer / Cash',
    currency: 'VND',
    invoiceStatus: 'invoiced',
    sapBillingDoc: '9000000001',
    items: [
      { id: 1, description: 'ERP Software – MM Module License', unit: 'License', qty: 1, unitPrice: 50000000, vatRate: 10 },
      { id: 2, description: 'Implementation Consulting Service', unit: 'Day', qty: 5, unitPrice: 8000000, vatRate: 10 },
    ],
    note: 'Payment via bank transfer',
  },
  {
    soNumber: '1000000002',
    soDate: '2024-05-08',
    deliveryDate: '2024-05-20',
    customer: {
      code: 'C002',
      name: 'XYZ Group Corporation',
      taxCode: '9876543210',
      address: '456 Le Loi St., Ben Thanh Ward, District 1, Ho Chi Minh City',
      phone: '028-3911-2222',
      email: 'finance@xyzgroup.com',
      bankAccount: '1234567890',
      bankName: 'Vietcombank',
    },
    buyerName: 'Sarah Mitchell',
    paymentMethod: 'Bank Transfer',
    currency: 'VND',
    invoiceStatus: 'pending',
    sapBillingDoc: null,
    items: [
      { id: 1, description: 'Accounting Software License', unit: 'Year', qty: 2, unitPrice: 30000000, vatRate: 10 },
    ],
    note: '',
  },
  {
    soNumber: '1000000003',
    soDate: '2024-05-10',
    deliveryDate: '2024-05-25',
    customer: {
      code: 'C004',
      name: 'VT Solutions Co., Ltd',
      taxCode: '0316964836',
      address: '15 Road No.9, Cityland Park Hills, Ward 10, Go Vap District, Ho Chi Minh City',
      phone: '028-3890-4444',
      email: 'finance@vtsolutions.vn',
      bankAccount: '9988776655',
      bankName: 'Techcombank',
    },
    buyerName: 'David Tran',
    paymentMethod: 'Bank Transfer',
    currency: 'VND',
    invoiceStatus: 'pending',
    sapBillingDoc: null,
    items: [
      { id: 1, description: 'Samsung Galaxy Note 10 Plus', unit: 'Unit', qty: 4, unitPrice: 18990000, vatRate: 10 },
      { id: 2, description: 'Samsung Galaxy Note 10', unit: 'Unit', qty: 6, unitPrice: 14990000, vatRate: 10 },
    ],
    note: '',
  },
  {
    soNumber: '1000000004',
    soDate: '2024-05-12',
    deliveryDate: '2024-05-28',
    customer: {
      code: 'C005',
      name: 'Hoang Long Trading JSC',
      taxCode: '0312345678',
      address: '88 Dien Bien Phu St., Ward 17, Binh Thanh District, Ho Chi Minh City',
      phone: '028-3514-5555',
      email: 'accounting@hoanglong.vn',
      bankAccount: '',
      bankName: '',
    },
    buyerName: 'Robert Pham',
    paymentMethod: 'Cash',
    currency: 'VND',
    invoiceStatus: 'pending',
    sapBillingDoc: null,
    items: [
      { id: 1, description: 'Software Consulting Service', unit: 'Day', qty: 10, unitPrice: 5000000, vatRate: 10 },
      { id: 2, description: 'Remote Technical Support', unit: 'Hour', qty: 20, unitPrice: 500000, vatRate: 10 },
    ],
    note: 'Priority processing before May 30',
  },
  {
    soNumber: '1000000006',
    soDate: '2024-05-13',
    deliveryDate: '2024-05-30',
    customer: {
      code: 'C006',
      name: 'Global Tech Import & Export Co.',
      taxCode: '0314567890',
      address: '200 Nguyen Van Linh Blvd, Tan Phong Ward, District 7, Ho Chi Minh City',
      phone: '028-5413-6666',
      email: 'finance@globaltech.vn',
      bankAccount: '1122334455',
      bankName: 'BIDV',
    },
    buyerName: 'Linda Nguyen',
    paymentMethod: 'Bank Transfer',
    currency: 'VND',
    invoiceStatus: 'pending',
    sapBillingDoc: null,
    items: [
      { id: 1, description: 'Cloud Infrastructure Setup', unit: 'Package', qty: 1, unitPrice: 85000000, vatRate: 10 },
      { id: 2, description: 'DevOps Consulting Service', unit: 'Day', qty: 8, unitPrice: 9500000, vatRate: 10 },
      { id: 3, description: 'Security Audit', unit: 'Time', qty: 1, unitPrice: 25000000, vatRate: 10 },
    ],
    note: 'Urgent — deploy before end of May',
  },
  {
    soNumber: '1000000007',
    soDate: '2024-05-14',
    deliveryDate: '2024-06-05',
    customer: {
      code: 'C007',
      name: 'Minh Phat Logistics JSC',
      taxCode: '0317891234',
      address: '45 Truong Son St., Ward 2, Tan Binh District, Ho Chi Minh City',
      phone: '028-3844-7777',
      email: 'accounting@minhphat.com.vn',
      bankAccount: '5566778899',
      bankName: 'Techcombank',
    },
    buyerName: 'Peter Vo',
    paymentMethod: 'Bank Transfer / Cash',
    currency: 'VND',
    invoiceStatus: 'pending',
    sapBillingDoc: null,
    items: [
      { id: 1, description: 'Warehouse Management Software License', unit: 'Year', qty: 1, unitPrice: 45000000, vatRate: 10 },
      { id: 2, description: 'Data Migration Service', unit: 'Day', qty: 5, unitPrice: 7500000, vatRate: 10 },
    ],
    note: '',
  },
  {
    soNumber: '1000000008',
    soDate: '2024-05-14',
    deliveryDate: '2024-06-10',
    customer: {
      code: 'C008',
      name: 'Sunrise Education Group',
      taxCode: '0319012345',
      address: '10 Tran Hung Dao St., Nguyen Cu Trinh Ward, District 1, Ho Chi Minh City',
      phone: '028-3920-8888',
      email: 'finance@sunrise-edu.vn',
      bankAccount: '6677889900',
      bankName: 'Vietcombank',
    },
    buyerName: 'Angela Pham',
    paymentMethod: 'Bank Transfer',
    currency: 'VND',
    invoiceStatus: 'pending',
    sapBillingDoc: null,
    items: [
      { id: 1, description: 'E-Learning Platform License', unit: 'Year', qty: 3, unitPrice: 20000000, vatRate: 10 },
      { id: 2, description: 'LMS Customization', unit: 'Hour', qty: 40, unitPrice: 800000, vatRate: 10 },
      { id: 3, description: 'Staff Training', unit: 'Day', qty: 2, unitPrice: 6000000, vatRate: 10 },
    ],
    note: 'Training to be scheduled after deployment',
  },
  {
    soNumber: '1000000005',
    soDate: '2024-04-01',
    deliveryDate: '2024-04-15',
    customer: {
      code: 'C003',
      name: 'DEF Solutions JSC',
      taxCode: '1122334455',
      address: '789 Hai Ba Trung St., Ward 8, District 3, Ho Chi Minh City',
      phone: '028-3930-3333',
      email: 'finance@defsolutions.vn',
      bankAccount: '',
      bankName: '',
    },
    buyerName: 'Michael Chen',
    paymentMethod: 'Cash',
    currency: 'VND',
    invoiceStatus: 'cancelled',
    sapBillingDoc: '9000000003',
    items: [
      { id: 1, description: 'System Maintenance Service', unit: 'Month', qty: 3, unitPrice: 15000000, vatRate: 8 },
    ],
    note: 'Cancelled per customer request',
  },
]

export const calcTotals = (items) => {
  const subtotal = items.reduce((sum, it) => sum + it.qty * it.unitPrice, 0)
  const vat = items.reduce((sum, it) => sum + it.qty * it.unitPrice * it.vatRate / 100, 0)
  return { subtotal, vat, total: subtotal + vat }
}
